export const SET_STEPS = "SET_STEPS";
export const INCREMENT_CURRENT_STEP = "INCREMENT_CURRENT_STEP";
export const DECREMENT_CURRENT_STEP = "DECREMENT_CURRENT_STEP";
export const STRIPE_PUBLIC =
	"pk_test_51LYvMMG6ZF9njpubGWnV5kHXjHHLl220MAxhMbChv7z3OnRmxCpswdGwutNkXdgb931D0efdOLhHsvP4yu67RJvL00d6GISPYO";
